### PR TITLE
APIX Update

### PR DESCRIPTION
**Pull request by damolitionn**
- Updated for APIX
- Replaced NameplateHandler hooks with AddonLifeCycle

### CODE REVIEW

**Comment by PunishedPineapple** [comment]
Thank you very much.  This looks like it leaves nameplate distances permanently enabled, but I will take care of that when I test things later.

**Comment by damolitionn** [comment]
Thanks for accepting my PR. In regards to the nameplate distances. From my testing, it looks like it's fine if this is what you mean?

With Nameplate distances toggled:
image

With Nameplate distanced turned off:
image

**Comment by PunishedPineapple** [comment]
Ya, it still hides the nodes in the checks for what to show, but it no longer stops updating the nodes completely when disabled.  I guess I need to check the update times again; if it is still performant with maximum people, I probably can just leave it always updating.  Either way, it's no big deal.  Thank you very much for doing this.

**Comment by damolitionn** [comment]
Oh I see now and no problem.

**Comment by mem5000** [comment]
Oh thank Bastet, you are working on this mod!  I can't judge the range for my standard/tech step with out it!

**Comment by PunishedPineapple** [comment]
Well, I tested things and submitted the new version, but [it unfortunately might be a while](https://github.com/goatcorp/DalamudPluginsD17/issues/3848) before it is available through the main plugin repo.

**Comment by mem5000** [comment]
Can it be added through the experimental section of dalamund?

**Comment by PunishedPineapple** [comment]
If you want to build it yourself, sure.  I guess I can try to put back up a third-party repo later, but like the safest thing would be to wait, since going into the main repo puts another set of eyes on it, especially with the new API.  I am honestly not sure how it would interact having a plugin on both the main repo and a third party repo with the same name, and I could see that screwing up updates in the future, so I need to think about it.

**Comment by mem5000** [comment]
ok, ill wait.  Thanks for working on this.  My dancer would hug you if she could.

**Pull request merged**
